<html><head>
<title>Заявка - <?=$comp_title?></title>
		<style type="text/css">
			td.brd {
				border: 1px solid black;
			}
		</style>
	</head>
	<body <? if(defined('AUTO_PRINT') and AUTO_PRINT){print "onLoad=\"window.print();\"";}?>>
		<div align=center>
		<table width=90% style="border: 1px solid black;" cellspacing=0>
			<tr><td colspan=2>
					<table width=100% border=0>
						<tr>
							<td>
								<img src=i/orr.gif>
							</td>
							<td align=center>
							<h1><?=$comp_title?></h1>
								<h1>ЗАЯВКА НА УЧАСТИЕ</h1>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td colspan=2><img src=i/sp.gif height=10></td></tr>

			<tr><td colspan=2 align=center><h2>Экипаж<?
			if($output['start_number'])
				print " № {$output['start_number']}";
			
			?></h2></td></tr>

			<tr><td colspan=2 align=left><h2>Пилот</h2></td></tr>
			<tr><td class=brd align=right width=30%><h3>ФИО, Ник:</h3></td><td class=brd>&nbsp;<b><?=$output['pilot_name']?></b></td></tr>
			<tr><td class=brd align=right width=30%><h3>Дата рождения:</h3></td><td class=brd>&nbsp;</td></tr>
			<?if(defined('USE_SIZE') and USE_SIZE){?>
				<tr><td class=brd align=right width=30%><h3>Размер одежды:</h3></td><td class=brd><h3>&nbsp;&nbsp;S / M / L / XL / XXL (подчеркнуть)</h3></td></tr>
			<?}?>
			<tr><td colspan=2><img src=i/sp.gif height=10></td></tr>

			<tr><td colspan=2 align=left><h2>Штурман</h2></td></tr>
			<tr><td class=brd align=right width=30%><h3>ФИО, Ник:</h3></td><td class=brd>&nbsp;<b><?=$output['navigator_name']?></td></tr>
			<tr><td class=brd align=right width=30%><h3>Дата рождения:</h3></td><td class=brd>&nbsp;</td></tr>
			<?if(defined('USE_SIZE') and USE_SIZE){?>
				<tr><td class=brd align=right width=30%><h3>Размер одежды:</h3></td><td class=brd><h3>&nbsp;&nbsp;S / M / L / XL / XXL (подчеркнуть)</h3></td></tr>
			<?}?>
			<tr><td colspan=2><img src=i/sp.gif height=10></td></tr>
			<tr><td colspan=2 align=left><h2>Контактные данные</h2></td></tr>
			<tr><td class=brd align=right width=30%><h3>Телефон(ы):</h3></td><td class=brd>&nbsp;<b><?=$output['phone']?></b></td></tr>
			<tr><td class=brd align=right width=30%><h3>E-Mail:</h3></td><td class=brd>&nbsp;<b><?=$output['email']?></b></td></tr>

			<tr><td colspan=2><img src=i/sp.gif height=10></td></tr>
			<tr><td colspan=2 align=center><h2>Автомобиль</h2></td></tr>
			<tr><td class=brd align=right width=30%><h3>Марка и модель:</h3></td><td class=brd>&nbsp;<b><?=$output['auto_brand']?></b></td></tr>
			<tr><td class=brd align=right width=30%><h3>Гос. номер:</h3></td><td class=brd>&nbsp;<b><?=$output['auto_number']?></b></td></tr>
<?if(defined('CA_WHEEL_SIZE') and CA_WHEEL_SIZE){?>
			<tr><td class=brd align=right width=30%><h3>Размер резины:</h3></td><td class=brd>&nbsp;<b><?=$output['wheel_size']?></b></td></tr>
<?}?>
			<tr><td class=brd align=right width=30%><h3>Класс (тех. ком.):</h3></td><td class=brd>&nbsp;<b><?=$output['class']?></b></td></tr>

			<tr><td colspan=2><img src=i/sp.gif height=10></td></tr>
			<tr><td colspan=2>
			<p>Экипаж заявляет о своём участии в соревнованиях внедорожных автомобилей и осведомлён обо всех рисках, связанных с этим. Экипаж не будет предъявлять организаторам соревнований никаких претензий в случае:</p>
			<ul>
				<li>получения травм кем-либо из членов экипажа;</li>
				<li>повреждения мне транспортного средства;</li>
				<li>нанесения ущерба мне или моему транспортному средству третьими лицами;</li>
			</ul>
			<p>Экипаж ознакомлен с правилами соревнований и согласен с их условиями без ограничений.
			<br />
			Экипаж подтверждает, что несёт полную ответственность перед третьими лицами в случае причинения им ущерба по вине членов экипажа. </p>
			</td>
			</tr>
			<tr><td colspan=2 align=left><h3>Ознакомлены и согласны</h3></td></tr>
			<tr><td colspan=2 align=right>
					<h3>Водитель:_____________________________ Дата:_______</h3>
			</td></tr>
			<tr><td colspan=2 align=right>
					<h3>Штурман:_____________________________ Дата:_______</h3>
			</td></tr>

			



		</table>
	</div>
	</body>
</head>
</html>
